

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/library"
    username: "root"
    password: "leejunkyu87"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddal-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

